# Generated by Django 4.0.1 on 2022-04-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='学号')),
                ('photo_path', models.CharField(max_length=64, verbose_name='路径')),
                ('temperature', models.FloatField(verbose_name='体温')),
            ],
        ),
    ]
