# Generated by Django 4.0.1 on 2022-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_abnormalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormalinfo',
            name='num',
            field=models.IntegerField(max_length=20, verbose_name='学号'),
        ),
    ]
