# Generated by Django 4.0.1 on 2022-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormalinfo',
            name='num',
            field=models.BigIntegerField(max_length=50, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(verbose_name='正文'),
        ),
    ]
