# Generated by Django 4.0.1 on 2022-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_abnormalinfo_num_alter_task_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abnormalinfo',
            name='num',
            field=models.BigIntegerField(verbose_name='学号'),
        ),
    ]
