# Generated by Django 4.0.1 on 2022-04-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_placelibrary_placeplayground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelibrary',
            name='create_time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='placeplayground',
            name='create_time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
