# Generated by Django 4.0.1 on 2022-04-23 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_placelibrary_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelibrary',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 7, 27, 51, 364030, tzinfo=utc), verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='placeplayground',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 7, 27, 51, 365027, tzinfo=utc), verbose_name='时间'),
        ),
    ]
