# Generated by Django 4.0.1 on 2022-04-23 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_placelibrary_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelibrary',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='placeplayground',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
