# Generated by Django 4.0.1 on 2022-04-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_placebasketballground_placediningroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebasketballground',
            name='temp',
            field=models.CharField(default='36.5', max_length=32, verbose_name='体温'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placediningroom',
            name='temp',
            field=models.CharField(default='36.5', max_length=32, verbose_name='体温'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placelibrary',
            name='temp',
            field=models.CharField(default='36.5', max_length=32, verbose_name='体温'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeplayground',
            name='temp',
            field=models.CharField(default='36.5', max_length=32, verbose_name='体温'),
            preserve_default=False,
        ),
    ]
