# Generated by Django 4.0.1 on 2022-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_placebasketballground_temp_placediningroom_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=16, verbose_name='温度')),
                ('humidity', models.CharField(max_length=16, verbose_name='相对湿度（单位：%）')),
                ('co2', models.CharField(max_length=16, verbose_name='二氧化碳浓度')),
                ('liquid', models.CharField(max_length=16, verbose_name='液体澄清程度')),
                ('gas', models.CharField(max_length=16, verbose_name='气体压力程度')),
                ('create_time', models.DateTimeField(verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='时间')),
                ('res', models.CharField(max_length=16, verbose_name='体温情况')),
                ('photo', models.CharField(max_length=128, verbose_name='人像')),
            ],
        ),
        migrations.AlterField(
            model_name='placelibrary',
            name='create_time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
